import type { Metadata } from "next";
import { Karla, Raleway } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { ThemeProvider } from "@/components/theme-provider";
import Header from "@/components/header";

const raleway = Raleway({subsets:['latin'],variable:'--font-sans'});

const karla = Karla({
  variable: '--font-karla',
	subsets: ['latin'],
	weight: ['400', '500', '800'],
})

export const metadata: Metadata = {
  title: "Better Auth Scorp App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
		<html
			lang='en'
			className={cn('font-sans', raleway.variable)}
			suppressHydrationWarning
		>
			<body className={`${karla.variable} antialiased min-h-[125vh]`}>
				<ThemeProvider
					attribute='class'
					defaultTheme='dark'
					enableSystem
					disableTransitionOnChange
				>
					<Header />
					{children}
				</ThemeProvider>
			</body>
		</html>
	)
}
